kind/feature request:
  title: '.*Add.*'

kind/enhancement:
  title: '.*(Improve|Change|Make|Convert).*'

kind/bug fix:
  title: '.*Fix.*'

status/WIP:
  title: 'WIP.*'

area/compatibility:
  title: '.*compat.*'

area/translations:
  title: '.*translation.*'

area/documentation:
  title: '.*(documentation|docs).*'

kind/documentation:
  title: '.*(documentation|docs).*'

area/tools:
  title: '.*tools.*'

ignore changelog:
  title: '.*tools.*'
