categories:
  - title: '**ADDED:**'
    labels:
      - 'kind/feature request'
      - 'kind/enhancement'
      - 'area/translations'
  - title: '**FIXED:**'
    labels:
      - 'kind/bug fix'
  - title: '**CHANGED:**'
    labels:
      - 'kind/enhancement'
      - 'kind/cleanup'
      - 'area/compatibility'
change-template: '- $TITLE (#$NUMBER)'
template: |
  _Requires CBA version X.Y.Z or later and Arma 3 version X.Y or later._

  ## Change Log Summary

  $CHANGES
