version: 2
jobs:
  build:
    docker:
      - image: thojkooi/ci-python
    steps:
      - checkout
      - run:
          name: Validate SQF And Config style
          command: python tools/sqf_validator.py && python tools/config_style_checker.py
  deployment:
    docker:
      - image: thojkooi/ci-python
    branch: master
    requires:
      - build
    steps:
      - checkout
      - deploy:
          name: Deploy
          command: |
            python3 tools/deploy.py
