version: 2
jobs:
  build:
    docker:
      - image: acemod/armake:master
    steps:
      - checkout
      - run:
          name: Validate SQF and Config style
          command: python tools/sqf_validator.py && python tools/config_style_checker.py
      - run:
          name: Version
          command: armake --version
      - run:
          name: Build
          command: |
            make -j 4
      - deploy:
          name: Update documentation and translation statistics
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ "${CIRCLE_PROJECT_USERNAME}" == "acemod" ]; then
              pip install pygithub pygithub3
              python3 tools/deploy.py
            else
              echo "Skipping, not on acemod/ACE3 master branch..."
            fi
  linting:
    docker:
      - image: acemod/sqflint:latest
    steps:
      - checkout
      - run:
          name: Lint sqf code
          command: sqflint --exit=e -d addons

workflows:
  version: 2
  build-job:
    jobs:
      - linting
      - build
