[sqf.banned_commands]
ignore = [
    "addPublicVariableEventHandler", # Alt syntax is broken, we are using main syntax
    "createSoundSource", # Greatly attenuated when in first person and in a vehicle
]
