name: Arma

on:
  push:
    branches:
    - master
  pull_request:

jobs:  
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Validate Config
      run: python3 tools/config_style_checker.py
    - name: Validate String tables
      run: python3 tools/check_strings.py
    # Currently broken
    #- name: Check for BOM
    #  uses: arma-actions/bom-check@master
    #  with:
    #    path: 'addons'

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Lint (sqflint)
      uses: arma-actions/sqflint@master
      continue-on-error: true # No failure due to many false-positives

  build:
    runs-on: ubuntu-latest
    container: acemod/armake:master
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Build (armake)
      run: armake --version && make -j4
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: ace3-nobin
        path: '@ace'
