name: Documentation

on:
  push:
    branches:
    - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Update documentation and translation statistics
      if: github.repository == 'acemod/ACE3' && "! contains(github.event.head_commit.message, '[ci skip]')"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python3 tools/deploy.py
